{"uuid": "4d60d362-e3c8-4cbd-8d15-b4e53fbce42a", "children": ["210dd98e-2a24-4ece-bb41-d55ddbe9d3e8"], "befores": [{"name": "_xunit_setup_method_fixture_TestMine", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up\n    at JWProxy.command (C:\\Users\\dd-33\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:236:13)\n", "trace": "  File \"e:\\test_huahua\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"E:\\test_huahua\\testcase\\test_mine.py\", line 8, in setup\n    self.mine = App().start().main().goto_mine()\n  File \"E:\\test_huahua\\page\\main.py\", line 35, in goto_mine\n    self.steps(\"../data/mine.yaml\", \"goto_mine\")\n  File \"E:\\test_huahua\\page\\base_page.py\", line 90, in steps\n    self.find(step[\"by\"], step[\"locator\"]).click()\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1703467611553, "stop": 1703467634221}], "start": 1703467611553, "stop": 1703467634314}