{"uuid": "87d53443-2119-4201-a8a0-c68a83906370", "children": ["d89f089a-7257-4a8b-85cd-94f536eb46a6"], "befores": [{"name": "_xunit_setup_method_fixture_TestMine", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"e:\\test_huahua\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"E:\\test_huahua\\testcase\\test_mine.py\", line 8, in setup\n    self.mine = App().start().main().goto_mine()\n  File \"E:\\test_huahua\\page\\app.py\", line 69, in main\n    WebDriverWait(self._driver, 60).until(wait_load)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1703238464657, "stop": 1703238535562}], "start": 1703238464657, "stop": 1703238535595}